# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import common
from . import test_acl
from . import test_base
from . import test_deprecation
from . import test_db_cursor
from . import test_display_name
from . import test_expression
from . import test_install
from . import test_avatar_mixin
from . import test_init
from . import test_ir_actions
from . import test_ir_asset
from . import test_ir_attachment
from . import test_ir_cron
from . import test_ir_filters
from . import test_ir_http
from . import test_ir_mail_server
from . import test_ir_mail_server_smtpd
from . import test_ir_model
from . import test_ir_module
from . import test_ir_sequence
from . import test_ir_embedded_actions
from . import test_ir_default
from . import test_ir_ui_menu
from . import test_module
from . import test_ir_qweb_fields
from . import test_ir_qweb
from . import test_res_config
from . import test_res_lang
from . import test_ir_actions_report
# from . import test_uninstall  # loop
from . import test_user_has_group
from . import test_views
from . import test_res_company
from . import test_res_currency
from . import test_res_country
from . import test_res_partner
from . import test_res_partner_bank
from . import test_res_partner_merge
from . import test_res_users
from . import test_reports
from . import test_form_create
from . import test_res_groups
